### ISSUE TITLE
CS0029: Cannot implicitly convert type 'Microsoft.DotNet.Interactive.PasswordString' to 'string'

### ISSUE THREAD

**Issue by TimKarsten** [johnmaeda/SK-How-Tos#8]
Hi,
running through your 2nd notebook "e2-first-dish" I get some errors on the first code block:
{
	"name": "Error",
	"message": "(95,26): error CS0029: Cannot implicitly convert type 'Microsoft.DotNet.Interactive.PasswordString' to 'string'\r
(100,26): error CS0029: Cannot implicitly convert type 'Microsoft.DotNet.Interactive.PasswordString' to 'string'"
}
{
	"name": "Error",
	"message": "(3,7): error CS0103: The name 'Settings' does not exist in the current context\r
(4,7): error CS0103: The name 'Settings' does not exist in the current context\r
(5,7): error CS0103: The name 'Settings' does not exist in the current context"
}

> #!import ../config/Settings.cs
> 
> bool useAzureOpenAI = false;
> 
> await Settings.AskAzureEndpoint(useAzureOpenAI);
> await Settings.AskModel(useAzureOpenAI);
> await Settings.AskApiKey(useAzureOpenAI);

First thing weird is that it doesn't import the Settings namespace, the file is present. I have the prerequisites and the first notebook executed fine.

**Comment by rewrlution** [comment]
@TimKarsten I encountered the same problem and I believed this PR can fix it - at least it worked in my local machine: https://github.com/johnmaeda/SK-Recipes/pull/9

**Comment by shyamsridhar123** [comment]
Error: (95,26): error CS1061: 'string' does not contain a definition for 'GetAwaiter' and no accessible extension method 'GetAwaiter' accepting a first argument of type 'string' could be found (are you missing a using directive or an assembly reference?)
(100,26): error CS1061: 'string' does not contain a definition for 'GetAwaiter' and no accessible extension method 'GetAwaiter' accepting a first argument of type 'string' could be found (are you missing a using directive or an assembly reference?)
Error: (3,7): error CS0103: The name 'Settings' does not exist in the current context
(4,7): error CS0103: The name 'Settings' does not exist in the current context
(5,7): error CS0103: The name 'Settings' does not exist in the current context

I added the tostring() and now getting this error message with the same notebook

**Comment by TimKarsten** [comment]
@rewrlution thanks for that PR!

Unfortunately this repo already appears more or less abandoned as there are PR's open since June.

**Comment by rewrlution** [comment]
@TimKarsten You are welcome. As a matter of fact, I realized that my PR was incorrect, since the `ToString()` method returns `**********` so that the secret is hidden in the `config/settings.json` file. In order to make it run, I need to go to `config/settings.json` to put a real secret there.

Unfortunately, I don't have a good fix for now, but the workaround is:
1. Use the `ToString()` method or something similar to make the compiler happy so that you can `import Settings`
2. After running that cell, go to `config/settings.json` to put the secret there.

In order to properly fix the issue, I will need to learn more about the functions that deal with `PasswordString`

**Comment by rewrlution** [comment]
@TimKarsten alright, I figured out I should use the `GetClearTextPassword()` instead of `ToString()`. I have tested it and the solution worked.

Ignore my last comment.

but yeah, it seems that the repo seems to be abandoned after June.

**Comment by TimKarsten** [comment]
Thanks @rewrlution , that makes a lot of sense!

Real shame this got abandoned so fast...
